DEBUG = True
SENDMAIL = '/usr/sbin/sendmail'
CONTACT_EMAIL = 'SET THIS TO YOUR CONTACT MAIL'
SECRET_KEY = 'SET THIS TO YOUR SECRET KEY'
PORTFOLIO_CURRENT = [
{'img': '/static/img/docman.png', 'alt': 'DocMan Screenshot', 'url': 'http://get.docman.me/', 'text': '<span class="bigger">DocMan</span> is a recent open source project we did using <span class="big">Django 1.3</span> and a huge load of third party Python libraries. It enables students to collaboratively manage documents related to their courses. <a href="http://get.docman.me/">More details?</a>', 'more': '<a href="http://get.docman.me/">Sign up for our beta</a> or <a href="https://github.com/piratesolutions/docman">check out the code on GitHub</a>.'},
{'img': '/static/img/kkgit.png', 'alt': 'Gitolite Administration Panel Screenshot', 'text': 'We love git, a beautiful tool for <span class="bigger">version control</span>, therefore we wrote a <span class="bigger"><a href="http://github.com/sitaramc/gitolite">Gitolite</a> administration panel</span> from scratch using <span class="big">Django 1.3</span> in under a week.', 'more': '<a href="http://git-scm.com/">Learn more about git</a> and <a href="http://en.wikipedia.org/wiki/Revision_control">version control</a>.'},
{'img': '/static/img/projektvm-small.png', 'alt': 'OpenVZ Hosting Panel Screenshot', 'url': 'https://vm.piratesolutions.org/', 'text': 'For our VPS hosting service, we wrote an <span class="bigger">OpenVZ hosting panel</span> with integrated <span class="bigger">CRM</span> from scratch using <span class="big">PHP 5.3</span>.'},]
PORTFOLIO_PAST = [
{'img': '/static/img/jpnw-small.png', 'alt': 'CRM Screenshot', 'text': 'We did an online <span class="bigger">CRM</span> for a registered association including <span class="bigger">event management</span> and <span class="bigger">badge printing API</span> using <span class="bigger">PHP 5.0</span>.'},
{'img': '/static/img/gg2-small.png', 'alt': 'Browser Game Screenshot', 'text': 'We were into developing and hosting of <span class="bigger">browser games</span>. We built strategic and role play games using <span class="bigger">PHP 5.2</span>, <span class="bigger">MySQL</span> and <span class="bigger">memcached</span>.'},
{'img': '/static/img/tickets-small.png', 'alt': 'Email Ticket System Screenshot', 'text': 'For dealing with <span class="bigger">customer business</span>, we designed a <span class="bigger">ticket request system</span> with web and email access on top of <span class="bigger">IMAP</span> protocol.'},
{'img': '/static/img/abm-small.png', 'alt': 'Content Management System Screenshot', 'text': '<span class="bigger">Content management</span> and <span class="bigger">online publishing</span> has been done by a school <span class="bigger">magazine</span> using our software solution.'},
{'img': '/static/img/htnbb-small.png', 'alt': 'Bulletin Board Screenshot', 'text': 'As a part of running browser games, we developed an <span class="bigger">integrated bulletin board</span> software using <span class="bigger">PHP 5.2</span>.'},]